### ISSUE TITLE
[Suggestion] Custom config to access all blocks

### ISSUE THREAD

**Issue by fernicar** [ljleb/comfy-mecha#4]
Amazing custom node, works great!
I would like to suggest a feature to input custom config to register a temp model arch, it should enable us to get access for:

- middle_block.0
- middle_block.1
- middle_block.2
- out.0
- out.2
- time_embed.0
- time_embed.2

which isn't posible without editing python's library files such as:
(PYTHON OR VENV)\Lib\site-packages\sd_mecha\models\sd1_ldm.yaml"
and restarting ComfyUI.
Perhaps a folder do load SD2/SD3 keys.txt too.

Here is an example workflow to test extra blocks and the config needed:
![request_custom_arch_config](https://github.com/user-attachments/assets/f723ada4-606a-4697-ae88-3a268d8ab947)

**Comment by ljleb** [comment]
Actually, there is an undocumented way of doing this. You can register a config the same way as the library does it:
https://github.com/ljleb/sd-mecha/blob/main/sd_mecha/builtin_model_archs.py

Calling `sd_mecha.extensions.model_arch.register_model_arch()` inside of the [`mecha_extensions` directory](https://github.com/ljleb/comfy-mecha/tree/main/mecha_extensions) will properly register new model types, regardless of how much they overlap with existing ones.

So you could define your own configs by copying the existing ones and then modifying them. Just be sure to use a different arch identifier, and to use the same identifier for all merge recipe inputs when using it.

I'm aware the current config style is not perfect, I am not super happy with having to specify all the keys manually for example. It would be nice to be able to generate them from pytorch code, if that can be made inexpensive / not require instantiating the memory of the model.

**Comment by fernicar** [comment]
Thanks, then I will use this 3 files as a mecha_extensions:
[comfy-mecha_sd15_with_31_blocks.zip](https://github.com/user-attachments/files/16373009/comfy-mecha_sd15_with_31_blocks.zip)
Here is the list of blocks again:
![request_custom_arch_config (2)](https://github.com/user-attachments/assets/aca51a5f-a772-4534-a912-8465bdf51760)
